// отслеживание и применение текущих установок языка при загрузке страницы
window.addEventListener('DOMContentLoaded', current_languag_setup);

//Обработка нажатия кнопки EN/RU c ИД en_ru:
document.getElementById('en_ru').addEventListener("click",change_language);

var currentLang = localStorage.getItem("langKey");//предварит. загрузка настройки языка из лок.хр.
if (currentLang == null){ //Если в хранилище еще пусто(первый заход на страницу)
    currentLang = "ru";} //Значение переменной, опред. установленный язык по умолчанию

//Массив, содерж.текст для рус и англ версий сайта
const languageDataArr = [["mein", "Главная", "Main"],  //Общая часть для всех страниц(начало)
                        ["about", "Про нас", "About"],
                        ["contacts" ,"Контакты", "Contacts"],
                        ["action", "Акции", "Action"],
                        ["games", "Игры", "Games"],
                        ["labirint", "<img src='img/lab2.jpg'>Лабиринт. Мини-РПГ-игра с прокачкой, поиском сокровищ, сражениями с врагами.", "<img src='img/lab2.jpg' >Labyrinth. Mini-RPG game with leveling, treasure hunting, battles with enemies."],
                        ["bj", "<img src='img/bla3.jpg' >Блэкджек. Карточная игра по традиционным правилам с зарабатыванием денег и топ-листом.", "<img src='img/bla3.jpg' >Blackjack. A card game with traditional rules, earning money and a top list."],
                        ["sb", "<img src='img/seb3.jpg' ></img>Морской бой. Игра из детства на поле размером 10 на 10 клеток против компьютерного оппонента.", "<img src='img/seb3.jpg' ></img>Sea Battle. A childhood game played on a 10x10 grid against a computer opponent."],
                        ["vic", "<img src='img/vic3.jpg' >Викторина с разными темами, случайной комбинацией вопросов и подсчетом очков в финале", "<img src='img/vic3.jpg' > A quiz with different topics, random combination of questions and scoring at the end"],
                        ["mein_down", "Главная", "Main"],
                        ["about_down", "О нас", "About"],
                        ["contacts_down", "Контакты", "Contacts"],
                        ["action_down", "Акции", "Action"],
                        ["top_down", "В начало страницы", "Top of page"],//Общая часть для всех страниц(конец)
                        ["title_casino","Казино с блэкджеком и лабиринтами","Casino with blackjack and labyrinths"],
                        ["inf_casino", "Казино с блэкджеком и лабиринтами", "Casino with blackjack and labyrinths"],
                        ["info", "Инфа, которая обычно бывает на главной странице сайта", "Info that is usually on the main page of a site"],
                        ["title_about", "Про нас", "About"], 
                        ["inf_comp", "Информация о компании", "Company information"],
                        ["company", "Компания ООО 'Казино с блэкджеком и лабиринтами'", "Company LLC 'Casino with blackjack and labyrinths'"],
                        ["OOO", "Компания ООО 'Казино с блекджеком и лабиринтами' – безусловный лидер в своей сфере деятельности.<br><br>Компания уже более 10 дней работает в омниканальной бизнес-модели и является игроком №2 в e-commerce. По состоянию на 1 февраля 2025 года сеть ООО 'Казино с блекджеком и лабиринтами' насчитывает овердофига филиалов. Компания ООО 'Казино с блекджеком и лабиринтами' — социально ответственная компания. Компания поддерживает экологические инициативы, направленные на ответственное потребление природных ресурсов и утилизацию отходов, и внедряет культуру DEI (разнообразия и инклюзивности).<br><br><img src='img/company3.jpg' class='img_main'>Важной составляющей стратегии развития компании является прозрачная и эффективная деятельность. Поэтому Компания ООО 'Казино с блекджеком и лабиринтами':Ответственно относится к выполнению обязательств перед государством и традиционно входит в Топ-100 крупнейших налогоплательщиков.<img src='img/company1.jpg' class='img_main'>Деятельность не лицензируется.<br><br>В стоимость любых товаров, работ, услуг, предлагаемых со стороны ООО 'Казино с блекджеком и лабиринтами' неограниченному кругу лиц, включены все налоги, предусмотренные законодательством.", "The company OOO 'Casino with blackjack and labyrinths' is an absolute leader in its field of activity.<br><br><br> The company has been working in the omnichannel business model for more than 10 days and is the №2 player in e-commerce. As of February 1, 2025, the network of OOO 'Casino with blackjack and labyrinths' has a ton of branches.The company OOO 'Casino with Blackjack and Labyrinths' is a socially responsible company. The company supports environmental initiatives aimed at responsible consumption of natural resources and waste disposal, and implements a DEI (diversity and inclusion) culture.<br><br><br><img src='img/company3.jpg' class='img_main'>An important component of the company's development strategy is transparent and efficient operations. Therefore, the Company OOO 'Casino with blackjack and labyrinths': Responsibly approaches the fulfillment of obligations to the state and is traditionally included in the Top 100 largest taxpayers.<img src='img/company1.jpg' class='img_main'>The activity is not licensed.<br><br>The cost of any goods, works, services offered by LLC 'Casino with blackjack and labyrinths' to an unlimited number of persons includes all taxes provided for by the legislation."],
                        ["title_action", "Акции", "Action"],
                        ["inf_cur_act", "Текущие акции:", "Current action:"],
                        ["month", "Только в этом месяце!", "This month only!"],
                        ["buy", "Купи две игры и получи третью в подарок!", "Buy two games and get the third one for free!"],
                        ["title_cont", "Контакты", "Contacts"],
                        ["inf_cont", "С нами можно связаться:", "You can contact us:"],
                        ["adress", "<img src='img/map.jpg' class='img_main'><br><br><li>Наш адрес: Улица Пушкина, дом Колотушкина</li><br><br><li>Наш телефон: 222-22-22, 222-33-33, 333-33-22</li><br><br><li>Наш @-мейл: 123@gmail.com</li>", "<img src='img/map.jpg' class='img_main'><br><br><li>Our address: Pushkin Street, Kolotushkin House</li><br><br><li>Our phone: 222-22-22, 222-33-33, 333-33-22</li><br><br><li>Our @-mail: 123@gmail.com</li>"],
                        ["title_bj", "Блэкджек", "Blackjack"],
                        ["info_bj", "Игра Блэкджек", "Blackjack game"],
                        ["description", "Краткое описание:", "Brief description:"],
                        ["bj1", "Карточная игра по традиционным правилам. На стартовом экране можно сменить настройки, ввести имя или подробнее ознакомиться с правилами. Цель игры- победить дилера, то есть компьютерного игрока, набрав большее количество очков, но не более двадцати одного. Очки набираются при открытии карт из колоды. Десятка, валет, дама, король- приносят по 10 очков. Туз- 1 либо 11 очков в зависимости от ситуации. Номерные карты приносят количество очков, соответственно своему номеру(двойка-2 очка, тройка-3, четверка-4 и т.д.).", "A card game with traditional rules. On the start screen you can change the settings, enter a name or read the rules in more detail.The goal of the game is to beat the dealer, i.e. the computer player, by scoring more points, but not more than twenty-one. Points are scored by opening cards from the deck. Ten, jack, queen, king - bring 10 points each. Ace - 1 or 11 points depending on the situation.Numbered cards bring the number of points corresponding to their number (two - 2 points, three - 3, four - 4, etc.)."],
                        ["bj2", "В левом верхнем углу экрана показан размер кошелька игрока, то есть оставшееся количество денег. В центре верхней части указана текущая ставка на следующий раунд.Игрок может либо увеличить, либо уменьшить ставку. Конечно, с нулевой ставкой начать раунд нельзя. Раунд начинается со сдачи двух карт игроку и двух карт дилеру. Далее игрок может либо открывать карты еще, либо остановиться и тогда ход переходит к оппоненту.", "The upper left corner of the screen shows the player's wallet size, i.e. the remaining amount of money. The current bet for the next round is shown in the upper center. The player can either increase or decrease the bet. Of course, you can't start a round with a zero bet. The round begins with two cards being dealt to the player and two cards to the dealer. The player can then either open more cards or stop, and then the turn goes to the opponent."],
                        ["bj3", "Игрок может открывать карты сколько угодно, но необходимо помнить, что набор более, чем 21 очка- обозначает перебор, то есть, проигрыш. Так же проигрышем будет, если игрок наберет очков меньше, чем оппонент. Если же игрок получает 21 очко  уже из первых двух карт- такая ситуация называется 'Блэкджек': игрок сразу выигрывает и его выигрыш увеличивается в полтора раза.", "The player can open cards as much as he wants, but it is necessary to remember that a set of more than 21 points means a bust, that is, a loss. It will also be a loss if the player scores fewer points than the opponent. If the player gets 21 points from the first two cards, this situation is called 'Blackjack': the player immediately wins and his winnings are increased by one and a half times."],
                        ["bj4", "Если игрок победил в раунде- сумма выигрыша прибавляется к сумме, имеющейся в кошельке. В случае проигрыша- сумма, которая была поставлена на кон, уходит дилеру.  В любой момент игрок может зафиксировать полученную в ходе игры сумму и завершить игру. В таком случае, игроку будет показана таблица рекордов.", "If the player wins the round, the winning amount is added to the amount in the wallet. In case of loss, the amount that was bet goes to the dealer. At any time, the player can fix the amount received during the game and end the game. In this case, the player will be shown a table of records."],
                        ["title_lab", "Лабиринт", "Labyrinth"],
                        ["info_lab", "Игра лабиринт", "Game labyrinth"],
                        ["lab1", "В этой игре Вам предстоит найти выход из лабиринта. На стартовом экране можно выбрать настройки игры.Первоначально все поле лабиринта скрыто от игрока и открывается постепенно по мере продвижения. По пути могут встретиться запертые двери, для которых надо найти соответствующий ключ, а также пузырьки восстановления здоровья, сундуки с сокровищами и, конечно же, враги.", "In this game you have to find a way out of the labyrinth. On the start screen you can select the game settings. Initially, the entire labyrinth field is hidden from the player and opens gradually as you progress. Along the way, you may encounter locked doors for which you need to find the appropriate key, as well as health recovery vials, treasure chests and, of course, enemies."],
                        ["lab2", "В левом верхнем углу экрана размещен портрет персонажа, а также полоски, показывающие текущий уровень здоровья и количество заработанных очков опыта. В нижнем левом углу- окно инвентаря, где отображаются найденные предметы, например, ключи. Когда игрок сталкивается в лабиринте с врагом, тот замечает персонажа и начинает движение в его сторону. Игрок может попытаться убежать либо сразиться. Если враг оказывается достаточно близко- начинается битва. Игрок и враг наносят друг другу удары.", "In the upper left corner of the screen there is a portrait of the character, as well as bars showing the current level of health and the amount of experience points earned. In the lower left corner there is an inventory window, where found items are displayed, such as keys. When the player encounters an enemy in the labyrinth, the enemy notices the character and begins to move towards him. The player can try to run away or fight. If the enemy is close enough, a battle begins. The player and the enemy strike each other."],
                        ["lab3", "Выиграв битву, игрок зарабатывает очки опыта. Когда количество очков опыта достигает необходимого предела- происходит повышение уровня, при котором повышаются характеристики персонажа. Таким образом, реализована прокачка.С каждым новым уровнем, количество очков опыта, необходимое для достижения следующего уровня возрастает", "By winning a battle, the player earns experience points. When the number of experience points reaches the required limit, a level increase occurs, at which the character's characteristics increase. Thus, pumping is implemented. With each new level, the number of experience points required to reach the next level increases."],
                        ["lab4", "Если игрок сумел найти выход, а также соответствующий ключ, то ему засчитывается победа. В ходе игры можно найти спрятанное за запертой дверью сокровище, а также набрать несколько уровней. Если же персонажа игрока убивают враги, то игра проиграна.", "If the player manages to find the exit and the corresponding key, then he wins. During the game, you can find a treasure hidden behind a locked door, and also gain several levels. If the player's character is killed by enemies, then the game is lost."],
                        ["title_sb", "Морской бой", "Sea battle"],
                        ["info_sb", "Игра Морской бой", "Game Sea battle"],
                        ["sb1", "Игра по традиционным правилам из детства. Игра происходит на поле размером 10 на 10 клеток. Игрок располагает свои корабли, затем  те же действия производит оппонент. При этом расположение своего флота игрок видит сразу,  а корабли противника необходимо вычислить и подбить в ходе сражения. Цель игры- потопить корабли противника раньше, чем он потопит корабли игрока. При запуске, игрок попадает на стартовый экран, где можно выбрать настройки.", "A game according to traditional rules from childhood. The game takes place on a field measuring 10 by 10 cells. The player places his ships, then the opponent does the same. The player sees the location of his fleet immediately, and the enemy ships must be calculated and destroyed during the battle. The goal of the game is to sink the enemy ships before he sinks the player's ships. When launched, the player is taken to the start screen where settings can be selected."],
                        ["sb2", "В начале игры игроку предлагается расставить свои корабли (один 4-палубный, два 3-палубных, три 2-палубных и четыре 1-палубных) согласно определенным правилам: Все корабли располагаются прямо, без изгибов. Корабли не могут располагаться в соседних клетках ни по горизонтали, ни по вертикали, ни по диагонали. Расстановка происходит автоматически при нажатии на кнопку. При необходимости расстановку кораблей можно поменять.", "At the beginning of the game, the player is asked to place his ships (one 4-deck, two 3-deck, three 2-deck and four 1-deck) according to certain rules: All ships are placed straight, without bends. Ships cannot be placed in adjacent cells either horizontally, vertically or diagonally. The placement occurs automatically when you press the button. If necessary, the arrangement of ships can be changed."],
                        ["sb3", "После расстановки кораблей, игрок получает право первого хода и может 'произвести выстрел' по любой выбранной незанятой клетке поля. В случае попадания, клетка помечается крестом и ход игрока продолжается. В случае промаха- клетка помечается точкой и ход передается оппоненту. Если вражеский корабль, по которому попал игрок, имеет еще целые палубы(клетки), то он считается 'раненым'. Если же целых палуб не остается, то этот корабль 'убит', помечается соответственно и выбывает из игры.", "After placing the ships, the player gets the right of the first move and can 'shoot' at any chosen unoccupied cell of the field. In case of a hit, the cell is marked with a cross and the player's turn continues. In case of a miss, the cell is marked with a dot and the turn passes to the opponent. If the enemy ship hit by the player still has whole decks (cells), then it is considered 'wounded'. If there are no whole decks left, then this ship is 'killed', marked accordingly and is eliminated from the game."],
                        ["sb4", "Игра считается завершенной когда у игрока или его оппонента заканчиваются корабли. (раненый корабль считается еще участвующим в сражении, пока его не убили окончательно). В случае, когда игрок убил все корабли противника- он считается победителем. В противоположной ситуации- проигравшим. В конце сражения на экран выводится информация о набранном количестве очков(в случае победы игрока). В случае проигрыша- очки не начисляются.", "The game is considered over when the player or his opponent runs out of ships. (A wounded ship is considered still participating in the battle until it is completely killed). In the case when a player has killed all the enemy ships, he is considered the winner. In the opposite situation, he is the loser. At the end of the battle, information about the number of points scored (if the player wins) is displayed on the screen. In case of loss, no points are awarded."],
                        ["title_vic", "Викторина", "Quiz"],
                        ["info_vic", "Игра Викторина", "Quiz game"],
                        ["vic1", "Викторина предлагает игроку на выбор несколько тем. После того, как тема викторины выбрана, случайным образом подбирается список из 10 вопросов,  на которые предлагается ответить игроку. Перед началом игры можно ввести имя, изменить настройки сложности.  В зависимости от выбранной сложности, игроку дается большее либо меньшее время для ответа на вопрос.", "The quiz offers the player several topics to choose from. After the quiz topic is selected, a list of 10 questions is randomly selected for the player to answer. Before the game starts, you can enter a name, change the difficulty settings. Depending on the selected difficulty, the player is given more or less time to answer the question."],
                        ["vic2", "Во время игры в верхней части экрана располагается панель состояния. На ней отображается количество правильных ответов, которые игрок дал на вопросы, текущий уровень сложности, имя, введенное игроком перед началом игры и время, оставшееся для ответа на текущий вопрос. После появления на экране вопроса, игроку предоставляется на выбор четыре варианта ответа. Если игрок выбирает верный вариант- ему засчитывается правильный ответ.", "During the game, there is a status bar at the top of the screen. It displays the number of correct answers the player has given to questions, the current difficulty level, the name the player entered before the game started, and the time remaining to answer the current question. Once a question appears on the screen, the player is given four answer options to choose from. If the player chooses the correct option, he is credited with the correct answer."],
                        ["vic3", "В случае выбора правильного ответа, игроку засчитывается один балл и выводится предложение перейти к следующему вопросу. Если же игрок выбирает неверный вариант- балл не засчитывается. В случае, если игрок не успевает ответить на вопрос за промежуток времени, соответствующий выбранной сложности, балл игроку также не засчитывается, на экран выводится сообщение о том, что время истекло, варианты ответов становятся недоступными для выбора, а игроку также предлагается перейти к следующему вопросу.", "If the correct answer is chosen, the player is awarded one point and is prompted to move on to the next question. If the player chooses the wrong option, the point is not awarded. If the player fails to answer the question within the time period corresponding to the selected difficulty, the player is not awarded a point, a message is displayed on the screen stating that the time has expired, the answer options become unavailable for selection, and the player is also asked to move on to the next question."],
                        ["vic4", "Игра считается завершенной, когда игроку будут представлены все вопросы викторины, согласно выбранной теме. После этого выводится экран финала игры, где представлена таблица рекордов. Если игрок набирает достаточное количество баллов для попадания в таблицу, то в ней отображается введенное перед началом игры имя и позиция в таблице. При этом, среди набравших одинаковое количество баллов игроков, выше в таблице будет располагаться тот игрок, который играл на более высокой сложности.", "The game is considered complete when the player is presented with all the quiz questions according to the selected topic. After that, the game final screen is displayed, where the leaderboard is presented. If the player scores enough points to get into the leaderboard, then the name entered before the start of the game and the position in the leaderboard are displayed. Moreover, among the players who scored the same number of points, the player who played at a higher difficulty level will be higher in the table."],
                    
                    ];
//console.log("Текущая настройка языка: " + localStorage.getItem("langKey"));
//console.log("Массив со словарем ру/енг: "+ languageDataArr);
//console.log("----------------------------");


function change_language(){ //Ф-ция смены языка- срабат. при нажатии на кнопку EN>RU
    if (currentLang == "ru") { //Если текущая установка языка- ру, то меняем на енг
        currentLang = "en";
        //localStorage.setItem("langKey", currentLang);//Сохр. в локальн. хр-ще под ключем langKey значение перем. отв. за текущ. уст. языка
        document.getElementById('en_ru').innerHTML ="EN>RU";//Меняем текст кнопки
    }
    else {currentLang = "ru"; //Если текущая установка языка- енг, то меняем на ру
          document.getElementById('en_ru').innerHTML ="RU>EN"//Меняем текст кнопки
    } 
    localStorage.setItem("langKey", currentLang);//Сохр. в локальн. хр-ще под ключем langKey значение перем. отв. за текущ. уст. языка
    //console.log("Текущая настройка языка" + currentLang);
    current_languag_setup();//Запускаем ф-цию установки языка (Ру либо Енг)согласно текущим настройкам
}

function current_languag_setup() {//ф-ция установки языка (Ру либо Енг)согласно текущим настройкам
    if (currentLang == "ru") {
        document.getElementById('en_ru').innerHTML ="RU>EN";//Меняем текст кнопки
        for (var i = 0; i < languageDataArr.length; i++){//Цикл для замены всех текстов на странице
            var el_id = languageDataArr[i][0];//Берем ИД след. элемента массива
            if (document.getElementById(el_id) != null){//Если элемент с таким ИД сущ. на странице(поиск по ид не возвр. нуль)
            document.getElementById(el_id).innerHTML =languageDataArr[i][1];//Меняем знач.англ. текста в элементе на рус.
            //console.log(el_id + languageDataArr[i][1]);//для проверки вывод в косноль
            }
        }
    }
    else {document.getElementById('en_ru').innerHTML ="EN>RU";
        for (var i = 0; i < languageDataArr.length; i++){
            var el_id = languageDataArr[i][0];//Берем ИД след. элемента массива
            if (document.getElementById(el_id) != null){//Если элемент с таким ИД сущ. на странице(поиск по ид не возвр. нуль)
            document.getElementById(el_id).innerHTML =languageDataArr[i][2]//Меняем знач.рус. текста в элементе на англ.
            //console.log(el_id + languageDataArr[i][2]); //для проверки вывод в косноль
            }
        }
    } 
}